[build]
publish = "."

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[headers]]
for = "/*.html"
[headers.values]
Content-Type = "text/html; charset=UTF-8"
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/sw.js"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=UTF-8"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/*.css"
[headers.values]
Content-Type = "text/css; charset=UTF-8"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=604800"
