name: Deploy Firebase Functions

# يشتغل تلقائياً لما تعدّل أي ملف في functions/
on:
  push:
    paths:
      - 'functions/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: سحب الكود
        uses: actions/checkout@v4

      - name: تثبيت Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: تثبيت المكتبات
        run: |
          cd functions
          npm install

      - name: نشر Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project hosainan-school
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
